# Gruvbox king 
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

# Make sure tmux can show correct color 
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true

decorations = "buttonless"
dynamic_title = true

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono"}
bold_italic = { family = "CaskaydiaCove Nerd Font Mono"}
size = 18

[cursor]
style = { shape = "Beam" }

[mouse]
hide_when_typing = true

# MacOS keybinding
[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001bB" },
  { key = "Right", mods = "Alt", chars = "\u001bF" },
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
  { key = "Back", mods = "Command", chars = "\u0015" },
]
